tempPath:     temp
resourceRoot:
databasePath: bot.db
ffmpegPath:

web:
  private:  localhost:14311
  public:

napCat:
  endpoint: ws://127.0.0.1:31001
  token:
  selfId:

divingFish:
  devToken:

lxns:
  devToken:

arcaea:
  resourcePath: arcaea
  tempPath:     arcaea
  assetsPath:

game:
  tempPath:     game

osu:
  clientId:
  clientSecret:
  tempPath:     osu
  resourcePath:

chunithm:
  resourcePath: chunithm
  tempPath:     chunithm
  tokenLouis:
  rinNetKeyChip:
  allNetKeyChip:
  
ongeki:
  resourcePath: ongeki
  tempPath:     ongeki

maimai:
  secret:
    maiSalt:    
    aimeSalt:   
    aesKey:     
    aesIv:      
  resourcePath: maimai
  tempPath:     maimai
  beatMapPath:

openai:
  endpoint:
  model:
  apiKey:

commander: []
