tempPath:     D:\Marisa\MarisaBotTemp
resourceRoot: D:\Marisa\MarisaBot-master\Marisa.Frontend\public\assets
databasePath: bot.db
ffmpegPath:

web:
  private:  localhost:14311
  public:

napCat:
  endpoint: ws://127.0.0.1:31001
  token: 96110
  selfId: 2035872327

divingFish:
  devToken:     QpLSJafqZHA5lyNjucmrgi69CEPWhT0e

lxns:
  devToken:     vJjiYA4eZBiFBC8Ev14DlH0drJEUemZnGMgsN05zEpg=
  oauth:
    clientId:   24b107b5-2519-40b5-a4e3-3827ee911663

arcaea:
  resourcePath: arcaea
  tempPath:     arcaea
  assetsPath:

game:
  tempPath:     game

osu:
  clientId:
  clientSecret:
  tempPath:     osu
  resourcePath:

chunithm:
  resourcePath: chunithm
  tempPath:     chunithm
  tokenLouis:
  rinNetKeyChip:
  allNetKeyChip:
  
ongeki:
  resourcePath: ongeki
  tempPath:     ongeki

maimai:
  secret:
    maiSalt:    
    aimeSalt:   
    aesKey:     
    aesIv:      
  resourcePath: maimai
  tempPath:     maimai
  beatMapPath:

openai:
  endpoint:
  model:
  apiKey:

commander: []
