// <auto-generated />
using System;
using Marisa.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Marisa.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20250404115900_chi")]
    partial class chi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("Marisa.EntityFrameworkCore.Entity.BlackList", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddTime")
                        .HasColumnType("TEXT");

                    b.Property<long>("UId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UId");

                    b.ToTable("BlackList");
                });

            modelBuilder.Entity("Marisa.EntityFrameworkCore.Entity.CommandFilter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prefix")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("CommandFilter");
                });

            modelBuilder.Entity("Marisa.EntityFrameworkCore.Entity.Plugin.Arcaea.ArcaeaGuess", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("TimesCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimesStart")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimesWrong")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UId");

                    b.ToTable("Arcaea.Guess");
                });

            modelBuilder.Entity("Marisa.EntityFrameworkCore.Entity.Plugin.Chunithm.ChunithmBind", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessCode")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long>("UId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UId");

                    b.ToTable("Chunithm.Bind");
                });

            modelBuilder.Entity("Marisa.EntityFrameworkCore.Entity.Plugin.Chunithm.ChunithmGuess", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("TimesCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimesStart")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimesWrong")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UId");

                    b.ToTable("Chunithm.Guess");
                });

            modelBuilder.Entity("Marisa.EntityFrameworkCore.Entity.Plugin.MaiMaiDx.MaiMaiDxBind", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AimeId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UId");

                    b.ToTable("MaiMaiDx.Bind");
                });

            modelBuilder.Entity("Marisa.EntityFrameworkCore.Entity.Plugin.MaiMaiDx.MaiMaiDxGuess", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("TimesCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimesStart")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimesWrong")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UId");

                    b.ToTable("MaiMaiDx.Guess");
                });

            modelBuilder.Entity("Marisa.EntityFrameworkCore.Entity.Plugin.Meal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Place")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Meal");
                });

            modelBuilder.Entity("Marisa.EntityFrameworkCore.Entity.Plugin.Ongeki.OngekiGuess", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("TimesCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimesStart")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimesWrong")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UId");

                    b.ToTable("Ongeki.Guess");
                });

            modelBuilder.Entity("Marisa.EntityFrameworkCore.Entity.Plugin.Osu.OsuBind", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GameMode")
                        .HasColumnType("TEXT");

                    b.Property<long>("OsuUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OsuUserName")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OsuUserId");

                    b.HasIndex("UserId");

                    b.ToTable("Osu.Bind");
                });

            modelBuilder.Entity("Marisa.EntityFrameworkCore.Entity.Plugin.Osu.OsuUserHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OsuUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OsuUserName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserInfo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OsuUserId");

                    b.HasIndex("OsuUserName");

                    b.ToTable("Osu.UserHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
